from time import sleep
import requests
import bs4
from selenium import webdriver

check = "No"
#PATH = "C:\Users\User\Downloads\J.A.R.V.I.S\Stock Market\chromedriver.exe"
driver = webdriver.Chrome('chromedriver.exe')
sleep(5)
driver.get("https://invest.motilaloswal.com/Home/LoginPage")
sleep(5)
login = driver.find_element_by_xpath("/html/body/div[2]/div[2]/div/div/div[2]/a")
login.click()
sleep(1)
username = driver.find_element_by_id("LoginId")
username.click()
sleep(1)
username.send_keys("8675983445")
password = driver.find_element_by_id("MainPassword")
password.click()
password.send_keys("ILVJune06")
sleep(1)
sleep(1)
enter = driver.find_element_by_id("btnLoginInv")
enter.click()
sleep(5)
watchlist = driver.find_element_by_xpath("/html/body/header/nav/div/div/div[2]/div[2]/ul/li[1]/a/img")
watchlist.click()
sleep(1)
search = driver.find_element_by_id("inputSearch")
search.click()
search.send_keys("Vodafone Idea")
sleep(1)
idea = driver.find_element_by_xpath("//*[@id='listData']/li[1]/div[1]/p[1]/a")
idea.click()
"""
username = driver.find_element_by_class_name("form-control")
username.click()
sleep(1)
username.send_keys("8675983445")
password = driver.find_element_by_id("MainPassword")
password.click()
sleep(1)
password.send_keys("ILVJune06")
sleep(1)
enter = driver.find_element_by_id("btnLoginInv")
enter.click()
sleep(10)
watchlist = driver.find_element_by_link_text("Watchlist")
watchlist.click()
"""
print("Vodafone IDEA")
while 1 == 1:
    sourceurl = requests.get('https://www.google.com/finance/quote/IDEA:NSE')
    gettext = bs4.BeautifulSoup(sourceurl.text, 'html.parser')
    sourcetag = gettext.find_all('div', attrs = {'class':'YMlKec fxKbKc'})
    sourcetag = str(sourcetag)
    sourcetag = sourcetag.replace('[<div class="YMlKec fxKbKc">₹', '')
    source = sourcetag.replace('</div>]', '')
    prevD = float(source)
    sleep(60/6)
    sourceurl1 = requests.get('https://www.google.com/finance/quote/IDEA:NSE')
    gettext1 = bs4.BeautifulSoup(sourceurl1.text, 'html.parser')
    sourcetag1 = gettext1.find_all('div', attrs = {'class':'YMlKec fxKbKc'})
    sourcetag1 = str(sourcetag1)
    sourcetag1 = sourcetag1.replace('[<div class="YMlKec fxKbKc">₹', '')
    source1 = sourcetag1.replace('</div>]', '')
    presD = float(source1)
    if prevD < presD:
        if check == "Yes":
            print("profit")
        elif check == "No":
            print("profit change")
            sleep(1)
            buy = driver.find_element_by_link_text("BUY")
            buy.click()
            sleep(1)
            quantity = driver.find_element_by_id("lQuantity")
            quantity.click()
            quantity.send_keys("147")
            sleep(1)
            market = driver.find_element_by_id("pills-market-tab")
            market.click()
            sleep(1)
            confirm_buy = driver.find_element_by_id("btnPlaceOrder")
            confirm_buy.click()
            sleep(1)
            d_o_b = driver.find_element_by_id("panOrderNumber")
            d_o_b.send_keys("19/09/1984")
            #sleep(1)
            #submit = driver.find_element_by_id("validatePancard")
            #submit.click()
            sleep(1)
            close = driver.find_element_by_xpath("//*[@id='dvOrderDataForm']/img")
            close.click()
            check = "Yes"
    elif prevD > presD:
        if check == "No":
            print("loss")
        elif check == "Yes":
            print("loss change")
            sleep(1)
            sell = driver.find_element_by_link_text("SELL")
            sell.click()
            sleep(1)
            quantity = driver.find_element_by_id("lQuantity")
            quantity.click()
            quantity.send_keys("147")
            sleep(1)
            market = driver.find_element_by_id("pills-market-tab")
            market.click()
            sleep(1)
            confirm_buy = driver.find_element_by_xpath("//*[@id='btnSellOrder']")
            confirm_buy.click()
            sleep(1)
            d_o_b = driver.find_element_by_id("panOrderNumber")
            d_o_b.send_keys("19/09/1984")
            #sleep(1)
            #submit = driver.find_element_by_id("validatePancard")
            #submit.click()
            sleep(1)
            close = driver.find_element_by_xpath("//*[@id='dvOrderDataForm']/img")
            close.click()
            check = "No"
    print(prevD, presD)
